export const allExecutions = [
  {
    runId: "RUN-234",
    suite: "Authentication Flow",
    project: "KAN",
    executor: "Sarah K.",
    started: "Jun 6 09:30",
    duration: "4m 12s",
    passed: 42,
    failed: 0,
    blocked: 0,
    status: "passed",
  },
  {
    runId: "RUN-233",
    suite: "User Management",
    project: "KAN",
    executor: "Mike R.",
    started: "Jun 6 08:45",
    duration: "6m 38s",
    passed: 33,
    failed: 5,
    blocked: 0,
    status: "partial",
  },
  {
    runId: "RUN-232",
    suite: "Regression Suite",
    project: "KAN",
    executor: "CI/CD Pipeline",
    started: "Jun 5 22:00",
    duration: "18m 44s",
    passed: 102,
    failed: 22,
    blocked: 0,
    status: "partial",
  },
  {
    runId: "RUN-231",
    suite: "Payment Processing",
    project: "SHOP",
    executor: "Alex J.",
    started: "Jun 5 16:20",
    duration: "9m 05s",
    passed: 56,
    failed: 0,
    blocked: 0,
    status: "passed",
  },
  {
    runId: "RUN-230",
    suite: "Search & Discovery",
    project: "SHOP",
    executor: "Tom B.",
    started: "Jun 4 11:15",
    duration: "3m 51s",
    passed: 18,
    failed: 6,
    blocked: 0,
    status: "failed",
  },
  {
    runId: "RUN-229",
    suite: "SSO Login Flow",
    project: "AUTH",
    executor: "Sarah K.",
    started: "Jun 4 10:00",
    duration: "2m 30s",
    passed: 22,
    failed: 0,
    blocked: 0,
    status: "passed",
  },
  {
    runId: "RUN-228",
    suite: "Notification Service",
    project: "KAN",
    executor: "Lisa M.",
    started: "Jun 3 15:40",
    duration: "1m 58s",
    passed: 17,
    failed: 0,
    blocked: 1,
    status: "partial",
  },
  {
    runId: "RUN-227",
    suite: "API Gateway Tests",
    project: "INFRA",
    executor: "CI/CD Pipeline",
    started: "Jun 3 06:00",
    duration: "5m 22s",
    passed: 21,
    failed: 10,
    blocked: 0,
    status: "failed",
  },
];

export const trendData = [
  { date: "Jun 1", passed: 187, failed: 23, blocked: 4 },
  { date: "Jun 2", passed: 201, failed: 18, blocked: 2 },
  { date: "Jun 3", passed: 156, failed: 31, blocked: 5 },
  { date: "Jun 4", passed: 224, failed: 15, blocked: 3 },
  { date: "Jun 5", passed: 191, failed: 28, blocked: 1 },
  { date: "Jun 6", passed: 75, failed: 11, blocked: 0 },
];

export const statusMap = {
  passed: { label: "Passed", cls: "bg-emerald-50 text-emerald-700" },
  partial: { label: "Partial", cls: "bg-blue-50 text-blue-700" },
  failed: { label: "Failed", cls: "bg-red-50 text-red-700" },
};
